# Generated by Django 5.2.5 on 2026-02-26 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkieTalkieGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'walkietalkie_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WalkieTalkieRecording',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_column='started_at')),
                ('ended_at', models.DateTimeField(db_column='ended_at')),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('storage_key', models.CharField(blank=True, max_length=1024, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='walkietalkie.walkietalkiegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkietalkie_recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walkietalkie_recordings',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WalkieTalkieGroupMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_column='joined_at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='walkietalkie.walkietalkiegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walkietalkie_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walkietalkie_group_members',
                'ordering': ['group', 'joined_at'],
                'constraints': [models.UniqueConstraint(fields=('group', 'user'), name='walkietalkie_group_member_unique')],
            },
        ),
    ]
