# Generated by Django 5.2.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walkietalkie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDriverVoiceMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1024)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.IntegerField(blank=True, default=48000, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, db_column='read_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_direct_voice_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_voice_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'walkietalkie_direct_voice_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='admindrivervoicemessage',
            index=models.Index(fields=['recipient', 'created_at'], name='wt_dvm_recipient_created'),
        ),
        migrations.AddIndex(
            model_name='admindrivervoicemessage',
            index=models.Index(fields=['sender', 'created_at'], name='wt_dvm_sender_created'),
        ),
    ]
