# Generated by Django 5.2.5 on 2026-02-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walkietalkie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walkietalkierecording',
            name='sample_rate',
            field=models.IntegerField(blank=True, default=16000, null=True),
        ),
    ]
