# Generated by Django 5.2.5 on 2026-03-10 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walkietalkie', '0002_admindrivervoicemessage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='admindrivervoicemessage',
            new_name='walkietalki_recipie_1d943f_idx',
            old_name='wt_dvm_recipient_created',
        ),
        migrations.RenameIndex(
            model_name='admindrivervoicemessage',
            new_name='walkietalki_sender__fc31bf_idx',
            old_name='wt_dvm_sender_created',
        ),
    ]
