# Generated by Django 6.0.1 on 2026-01-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=100)),
                ('otp_code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(default=False)),
                ('reset_token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'otp_verifications',
                'indexes': [models.Index(fields=['phone', 'is_used'], name='otp_verific_phone_3bb9e6_idx'), models.Index(fields=['reset_token'], name='otp_verific_reset_t_20b8a7_idx')],
            },
        ),
    ]
