# Generated by Django 5.2.5 on 2026-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_otpverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='to_be_pay',
            new_name='to_pay',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='to_be_received',
            new_name='to_receive',
        ),
        migrations.AddField(
            model_name='supersetting',
            name='gps_threshold',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
        ),
    ]
