# Generated by Django 5.2.5 on 2026-02-13 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wallet_rename_and_super_setting_gps'),
    ]

    operations = [
        migrations.AddField(
            model_name='supersetting',
            name='seat_layout',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='is_ticket_dealer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/licenses/'),
        ),
        migrations.AddField(
            model_name='user',
            name='license_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ticket_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cards',
                'indexes': [models.Index(fields=['card_number'], name='cards_card_nu_251768_idx'), models.Index(fields=['user'], name='cards_user_id_8f5cc7_idx')],
            },
        ),
    ]
