# Generated by Django 5.2.5 on 2026-02-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_seat_layout_user_license_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.card'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['card'], name='transaction_card_id_660ff7_idx'),
        ),
    ]
