# Generated by Django 5.2.5 on 2026-02-19 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_location_course'),
        ('core', '0007_supersetting_stop_point_announcement_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paisa', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('reference_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('connectips_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('connectips_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('purpose', models.CharField(choices=[('wallet_deposit', 'Wallet Deposit'), ('card_topup', 'Card Topup'), ('vehicle_ticket_booking', 'Vehicle Ticket Booking')], default='wallet_deposit', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='core.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL)),
                ('vehicle_ticket_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='booking.vehicleticketbooking')),
            ],
            options={
                'db_table': 'payment_transactions',
                'indexes': [models.Index(fields=['user'], name='payment_tra_user_id_b3ceaf_idx'), models.Index(fields=['status'], name='payment_tra_status_137fde_idx'), models.Index(fields=['purpose'], name='payment_tra_purpose_9977da_idx')],
            },
        ),
    ]
