# Generated by Django 5.2.5 on 2026-03-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_contact_messages',
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/website/site/')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('tagline', models.CharField(blank=True, default='', max_length=500)),
                ('phones', models.JSONField(blank=True, default=list)),
                ('emails', models.JSONField(blank=True, default=list)),
                ('address', models.TextField(blank=True, default='')),
                ('map', models.TextField(blank=True, default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='uploads/website/site/')),
                ('footer_text', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_site_settings',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/website/blog/')),
                ('content', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_blogs',
                'indexes': [models.Index(fields=['slug'], name='website_blo_slug_2e15af_idx'), models.Index(fields=['is_active'], name='website_blo_is_acti_446772_idx')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_faqs',
                'indexes': [models.Index(fields=['is_active'], name='website_faq_is_acti_4b76c8_idx'), models.Index(fields=['order'], name='website_faq_order_1d0879_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('svg', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_services',
                'indexes': [models.Index(fields=['slug'], name='website_ser_slug_227a5d_idx'), models.Index(fields=['is_active'], name='website_ser_is_acti_268a2b_idx'), models.Index(fields=['order'], name='website_ser_order_d62682_idx')],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/website/sliders/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_sliders',
                'indexes': [models.Index(fields=['is_active'], name='website_sli_is_acti_02d5c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/website/team/')),
                ('designation', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_team',
                'indexes': [models.Index(fields=['is_active'], name='website_tea_is_acti_c67e24_idx'), models.Index(fields=['order'], name='website_tea_order_111aed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('star', models.IntegerField(default=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/website/testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'website_testimonials',
                'indexes': [models.Index(fields=['is_active'], name='website_tes_is_acti_e97948_idx')],
            },
        ),
        migrations.CreateModel(
            name='CMSPage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/website/cms/')),
                ('content', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_footer', models.BooleanField(default=False)),
                ('is_header', models.BooleanField(default=False)),
                ('is_about', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('section_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sections', to='website.cmspage')),
            ],
            options={
                'db_table': 'website_cms_pages',
                'indexes': [models.Index(fields=['slug'], name='website_cms_slug_aed2a3_idx'), models.Index(fields=['is_active', 'is_about'], name='website_cms_is_acti_d6bf59_idx'), models.Index(fields=['is_active', 'is_header'], name='website_cms_is_acti_8bc2a3_idx'), models.Index(fields=['section_in'], name='website_cms_section_6a7431_idx')],
            },
        ),
    ]
