# Generated by Django 5.2.5 on 2026-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_add_service_icon_blog_excerpt_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/website/site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vision',
            field=models.TextField(blank=True, default=''),
        ),
    ]
