"""
Django settings for ev_yatayat_sewa_server project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ew=#_)139h93ci-ezp4ark5ie!$=b)&=#mu(5c=y@j6$x$6@h-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'booking',
    'walkietalkie',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

# Custom User Model
AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
}
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'ev_yatayat_sewa_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ev_yatayat_sewa_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Uses PyMySQL (see __init__.py) when ENGINE is django.db.backends.mysql

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': os.environ.get('DB_NAME', 'ev_yatayat_sewa'),
    #     'USER': os.environ.get('DB_USER', 'root'),
    #     'PASSWORD': os.environ.get('DB_PASSWORD', ''),
    #     'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
    #     'PORT': os.environ.get('DB_PORT', '3306'),
    #     'OPTIONS': {
    #         'charset': 'utf8mb4',
    #     },
    # }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kathmandu'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, 'static')
# ] 
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# NCHL ConnectIPS Payment Gateway
NCHL_MERCHANT_ID = int(os.environ.get('NCHL_MERCHANT_ID', '4242'))
NCHL_APP_ID = os.environ.get('NCHL_APP_ID', 'MER-4242-APP-1')
NCHL_APP_NAME = os.environ.get('NCHL_APP_NAME', 'E.V.Yatayat Sewa Pvt.Ltd.')
NCHL_APP_PASSWORD = os.environ.get('NCHL_APP_PASSWORD', 'Ev@yatayat#4321')
NCHL_PFX_PATH = os.environ.get('NCHL_PFX_PATH', 'EVYATAYAT.pfx')
NCHL_PFX_PASSWORD = os.environ.get('NCHL_PFX_PASSWORD', 'Evy@tay@t321')
NCHL_BASE_URL = os.environ.get('NCHL_BASE_URL', 'https://login.connectips.com').rstrip('/')
# Resolve PFX path: relative to BASE_DIR or absolute
if not os.path.isabs(NCHL_PFX_PATH):
    NCHL_PFX_PATH = str(BASE_DIR / NCHL_PFX_PATH)
FRONTEND_URL = os.environ.get('FRONTEND_URL', '').rstrip('/')

# Walkie-Talkie: directory where Node saves recording files (same as Node RECORDINGS_PATH in production)
WALKIETALKIE_RECORDINGS_DIR = '/home/luna/apps/EV-Yatayat-Sewa-Node/recordings'
