# Generated by Django 6.0.1 on 2026-01-21 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overspeed_limit', models.IntegerField(default=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='uploads/vehicles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/vehicles/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicle_images',
            },
        ),
        migrations.CreateModel(
            name='VehicleSeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicle_seats',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'places',
                'indexes': [models.Index(fields=['code'], name='places_code_593959_idx'), models.Index(fields=['latitude', 'longitude'], name='places_latitud_9cc1dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_bidirectional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending_here', to='booking.place')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='booking.place')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteStopPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='booking.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_points', to='booking.route')),
            ],
            options={
                'db_table': 'route_stop_points',
            },
        ),
    ]
