# Generated by Django 5.2.5 on 2026-03-04 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('course', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imei', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('odometer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overspeed_limit', models.IntegerField(default=80)),
                ('description', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='uploads/vehicles/')),
                ('is_active', models.BooleanField(default=True)),
                ('bill_book', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_book_expiry_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('road_permit_expiry_date', models.DateField(blank=True, null=True)),
                ('seat_layout', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicles',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='uploads/vehicles/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicle_images',
            },
        ),
        migrations.CreateModel(
            name='VehicleSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicle_schedules',
            },
        ),
        migrations.CreateModel(
            name='VehicleSeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicle_seats',
            },
        ),
        migrations.CreateModel(
            name='VehicleTicketBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('ticket_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('seat', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('pnr', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'vehicle_ticket_bookings',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'places',
                'indexes': [models.Index(fields=['code'], name='places_code_593959_idx'), models.Index(fields=['latitude', 'longitude'], name='places_latitud_9cc1dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_bidirectional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('end_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_ending_here', to='booking.place')),
                ('start_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_starting_here', to='booking.place')),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='RouteStopPoint',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('announcement_text', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='booking.place')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_points', to='booking.route')),
            ],
            options={
                'db_table': 'route_stop_points',
            },
        ),
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('check_in_lat', models.DecimalField(decimal_places=16, max_digits=20)),
                ('check_in_lng', models.DecimalField(decimal_places=16, max_digits=20)),
                ('check_in_datetime', models.DateTimeField()),
                ('check_in_address', models.TextField()),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('check_out_datetime', models.DateTimeField(blank=True, null=True)),
                ('check_out_address', models.TextField(blank=True, null=True)),
                ('trip_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_duration', models.IntegerField(blank=True, null=True)),
                ('trip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('destination_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings_destination', to='booking.place')),
            ],
            options={
                'db_table': 'seat_bookings',
            },
        ),
    ]
