# Generated by Django 5.2.5 on 2026-03-04 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.route'),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to='booking.trip'),
        ),
        migrations.AddField(
            model_name='location',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='booking.trip'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles_route', to='booking.route'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_driver': True}, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='booking.route'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='location',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleschedule',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_schedules', to='booking.route'),
        ),
        migrations.AddField(
            model_name='vehicleschedule',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_schedules', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='booking.vehicleschedule'),
        ),
        migrations.AddField(
            model_name='vehicleseat',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='vehicle_seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.vehicleseat'),
        ),
        migrations.AddField(
            model_name='vehicleticketbooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleticketbooking',
            name='destination_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_bookings_destination', to='booking.place'),
        ),
        migrations.AddField(
            model_name='vehicleticketbooking',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_bookings_pickup', to='booking.place'),
        ),
        migrations.AddField(
            model_name='vehicleticketbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_ticket_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicleticketbooking',
            name='vehicle_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bookings', to='booking.vehicleschedule'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['start_point', 'end_point'], name='routes_start_p_e2788f_idx'),
        ),
        migrations.AddIndex(
            model_name='routestoppoint',
            index=models.Index(fields=['route', 'place'], name='route_stop__route_i_7fc056_idx'),
        ),
        migrations.AddIndex(
            model_name='routestoppoint',
            index=models.Index(fields=['route', 'order'], name='route_stop__route_i_030e7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestoppoint',
            unique_together={('route', 'place')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_no'], name='vehicles_vehicle_e9913e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['imei'], name='vehicles_imei_892831_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='vehicles_is_acti_fa11c1_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['vehicle', 'created_at'], name='locations_vehicle_28ed95_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['trip', 'created_at'], name='locations_trip_id_c7c20f_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['vehicle'], name='vehicle_ima_vehicle_210923_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleschedule',
            index=models.Index(fields=['vehicle', 'date'], name='vehicle_sch_vehicle_9dbd74_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleschedule',
            index=models.Index(fields=['route', 'date'], name='vehicle_sch_route_i_61ec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'start_time'], name='trips_vehicle_c509df_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'start_time'], name='trips_driver__629cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route'], name='trips_route_i_06d09d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['end_time'], name='trips_end_tim_ba0955_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleseat',
            index=models.Index(fields=['vehicle', 'status'], name='vehicle_sea_vehicle_1b0e86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleseat',
            unique_together={('vehicle', 'side', 'number')},
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['vehicle', 'vehicle_seat'], name='seat_bookin_vehicle_10c3ed_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['user'], name='seat_bookin_user_id_4ff009_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['is_guest'], name='seat_bookin_is_gues_f96269_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['is_paid'], name='seat_bookin_is_paid_6daf21_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['check_in_datetime'], name='seat_bookin_check_i_1e5307_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['vehicle_seat', 'check_out_datetime'], name='seat_bookin_vehicle_65a5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['vehicle_schedule'], name='vehicle_tic_vehicle_9162b9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['user'], name='vehicle_tic_user_id_84e128_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['booked_by'], name='vehicle_tic_booked__dc9fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['pnr'], name='vehicle_tic_pnr_356021_idx'),
        ),
    ]
