# Generated by Django 6.0.1 on 2026-01-21 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='active_driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_driver': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='active_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_vehicles_route', to='booking.route'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='drivers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_driver': True}, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='routes',
            field=models.ManyToManyField(blank=True, related_name='vehicles', to='booking.route'),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleseat',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.vehicle'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['start_point', 'end_point'], name='routes_start_p_e2788f_idx'),
        ),
        migrations.AddIndex(
            model_name='routestoppoint',
            index=models.Index(fields=['route', 'place'], name='route_stop__route_i_7fc056_idx'),
        ),
        migrations.AddIndex(
            model_name='routestoppoint',
            index=models.Index(fields=['route', 'order'], name='route_stop__route_i_030e7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routestoppoint',
            unique_together={('route', 'place')},
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['vehicle_no'], name='vehicles_vehicle_e9913e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['imei'], name='vehicles_imei_892831_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='vehicles_is_acti_fa11c1_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleimage',
            index=models.Index(fields=['vehicle'], name='vehicle_ima_vehicle_210923_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleseat',
            index=models.Index(fields=['vehicle', 'status'], name='vehicle_sea_vehicle_1b0e86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicleseat',
            unique_together={('vehicle', 'side', 'number')},
        ),
    ]
