# Generated by Django 5.2.5 on 2026-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='reverse_direction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicleschedule',
            name='reverse_direction',
            field=models.BooleanField(default=False),
        ),
    ]
