# Generated by Django 5.2.5 on 2026-01-24 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('check_in_lat', models.DecimalField(decimal_places=16, max_digits=20)),
                ('check_in_lng', models.DecimalField(decimal_places=16, max_digits=20)),
                ('check_in_datetime', models.DateTimeField()),
                ('check_in_address', models.TextField()),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('check_out_datetime', models.DateTimeField(blank=True, null=True)),
                ('check_out_address', models.TextField(blank=True, null=True)),
                ('trip_distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_duration', models.IntegerField(blank=True, null=True)),
                ('trip_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_bookings', to='booking.vehicle')),
                ('vehicle_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.vehicleseat')),
            ],
            options={
                'db_table': 'seat_bookings',
                'indexes': [models.Index(fields=['vehicle', 'vehicle_seat'], name='seat_bookin_vehicle_10c3ed_idx'), models.Index(fields=['user'], name='seat_bookin_user_id_4ff009_idx'), models.Index(fields=['is_guest'], name='seat_bookin_is_gues_f96269_idx'), models.Index(fields=['is_paid'], name='seat_bookin_is_paid_6daf21_idx'), models.Index(fields=['check_in_datetime'], name='seat_bookin_check_i_1e5307_idx'), models.Index(fields=['vehicle_seat', 'check_out_datetime'], name='seat_bookin_vehicle_65a5fb_idx')],
            },
        ),
    ]
