# Generated by Django 5.2.5

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_add_reverse_direction_to_trip_and_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='origin_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings_origin', to='booking.place'),
        ),
    ]
