# Generated by Django 5.2.5 on 2026-02-11 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_seatbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('trip_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_scheduled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('driver', models.ForeignKey(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='booking.vehicle')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings', to='booking.trip'),
        ),
        migrations.CreateModel(
            name='VehicleSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_schedules', to='booking.route')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_schedules', to='booking.vehicle')),
            ],
            options={
                'db_table': 'vehicle_schedules',
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='vehicle_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='booking.vehicleschedule'),
        ),
        migrations.CreateModel(
            name='VehicleTicketBooking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_guest', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=100)),
                ('ticket_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('seat', models.JSONField(default=dict)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('pnr', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_ticket_bookings', to=settings.AUTH_USER_MODEL)),
                ('vehicle_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_bookings', to='booking.vehicleschedule')),
            ],
            options={
                'db_table': 'vehicle_ticket_bookings',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=20)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='booking.vehicle')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='booking.trip')),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['vehicle', 'created_at'], name='locations_vehicle_28ed95_idx'), models.Index(fields=['trip', 'created_at'], name='locations_trip_id_c7c20f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='vehicleschedule',
            index=models.Index(fields=['vehicle', 'date'], name='vehicle_sch_vehicle_9dbd74_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleschedule',
            index=models.Index(fields=['route', 'date'], name='vehicle_sch_route_i_61ec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle', 'start_time'], name='trips_vehicle_c509df_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'start_time'], name='trips_driver__629cd5_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route'], name='trips_route_i_06d09d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['end_time'], name='trips_end_tim_ba0955_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['vehicle_schedule'], name='vehicle_tic_vehicle_9162b9_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['user'], name='vehicle_tic_user_id_84e128_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['pnr'], name='vehicle_tic_pnr_356021_idx'),
        ),
    ]
