# Generated by Django 5.2.5 on 2026-02-13 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_add_vehicle_seat_layout_and_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleticketbooking',
            name='booked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vehicleticketbooking',
            index=models.Index(fields=['booked_by'], name='vehicle_tic_booked__dc9fa1_idx'),
        ),
    ]
