# Generated by Django 5.2.5 on 2026-02-15 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_vehicleticketbooking_pickup_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbooking',
            name='destination_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_bookings_destination', to='booking.place'),
        ),
    ]
